@startuml

!include ../C4_Container.puml

title Контекстная диаграмма системы «Тёплый дом»

Person(User, "Пользователь")
Person(Master, "Специалист")

System(Monolith, "Система «Тёплый дом»", "Монолитное приложение")
System_Ext(Devices, "Внешние устройства (датчики)")

Rel(Master, Monolith, "подключение датчиков отопления и температуры")
Rel(User, Monolith, "включение/выключение отопления, настройка/просмотр температуры")

Rel(Monolith, Devices, "управление датчиками отопления, запрашивает данные о температуре")
Rel(Devices, Monolith, "отправляет данные о температуре")

@enduml